#!/usr/bin/env ruby
# Encoding: UTF-8

################################################################################
# CSS colours.
# http://c0ffee.surge.sh/
################################################################################
# Uses the POS tag set defined here:
#   https://github.com/yohasebe/engtagger#tag-set
# With the additions:
#   VBT = transitive verb
#   VBI = intransitive verb
################################################################################

# https://en.wiktionary.org/wiki/sasses#English

module CSSColours
  WORDS_POS = [
    ["abased", ["VBD"]],
    ["abases", ["VBZ"]],
    ["abated", ["VBD"]],
    ["abates", ["VBZ"]],
    ["abbess", ["NN"]],
    ["abbots", ["NNS"]],
    ["abided", ["VBD"]],
    ["abides", ["VBZ"]],
    ["aboded", ["VBD"]],
    ["abodes", ["NNS"]],
    ["acacia", ["NN"]],
    ["accede", ["VBI"]],
    ["access", ["NN"]],
    ["accost", ["VBT", "NN"]],
    ["acetic", ["JJ"]],
    ["acidic", ["JJ"]],
    ["addict", ["VBT", "NN"]],
    ["adobes", ["NNS"]],
    ["affect", ["NN", "VBT", "VBI"]],
    ["assess", ["VBT"]],
    ["assets", ["NNS"]],
    ["assist", ["VBT", "VBI", "NN"]],
    ["attest", ["VBT", "VBI"]],
    ["attics", ["NNS"]],
    ["babied", ["VBD"]],
    ["babies", ["VBZ","NNS"]],
    ["baited", ["VBD"]],
    ["basest", ["JJS"]],
    ["basics", ["NNS"]],
    ["basses", ["NNS"]],
    ["basset", ["NN"]],
    ["basted", ["VBD"]],
    ["bastes", ["VBZ"]],
    ["batted", ["VBD"]],
    ["beaded", ["VBD", "JJ"]],
    ["beasts", ["NNS"]],
    ["bedded", ["VBD"]],
    ["beefed", ["VBD"]],
    ["befits", ["VBZ"]],
    ["besets", ["VBZ"]],
    ["beside", ["?"]],
    ["besots", ["VBZ"]],
    ["bested", ["VBD"]],
    ["betide", ["VBT"]],
    ["biased", ["VBD","JJ"]],
    ["biases", ["VBZ","NNS"]],
    ["bidets", ["NNS"]],
    ["biotas", ["NNS"]],
    ["biotic", ["JJ"]],
    ["bisect", ["VBT"]],
    ["bitted", ["VBD"]],
    ["boasts", ["VBZ"]],
    ["boated", ["VBD"]],
    ["bobbed", ["VBD"]],
    ["bobcat", ["NN"]],
    ["bodice", ["NN"]],
    ["bodied", ["VBD"]],
    ["bodies", ["NNS"]],
    ["boffos", ["NNS"]],
    ["boobed", ["VBD"]],
    ["booboo", ["NN"]],
    ["boosed", ["VBD"]],
    ["booses", ["NNS"]],
    ["boosts", ["VBZ","NNS"]],
    ["booted", ["VBD"]],
    ["bossed", ["VBD"]],
    ["bosses", ["VBZ","NNS"]],
    ["cabbed", ["VBD"]],
    ["cacaos", ["NNS"]],
    ["caddie", ["NN"]],
    ["cadets", ["NNS"]],
    ["casted", ["VBD"]],
    ["castes", ["NNS"]],
    ["catted", ["VBD"]],
    ["ceased", ["VBD"]],
    ["ceases", ["VBZ"]],
    ["cicada", ["NN"]],
    ["cities", ["NNS"]],
    ["coasts", ["VBZ","NNS"]],
    ["coated", ["VBD"]],
    ["cobbed", ["VBD"]],
    ["cocoas", ["NNS"]],
    ["codded", ["VBD"]],
    ["coedit", ["VBI"]],
    ["coffee", ["NN"]],
    ["cootie", ["NN"]],
    ["cosies", ["VBZ"]],
    ["dabbed", ["VBD"]],
    ["dacite", ["NN"]],
    ["dadoes", ["NNS"]],
    ["daises", ["NNS"]],
    ["debase", ["VBT"]],
    ["debate", ["VBI"]],
    ["debits", ["VBZ","NNS"]],
    ["decade", ["NN"]],
    ["deceit", ["NN"]],
    ["decide", ["VBT", "VBI"]],
    ["decoct", ["VBT"]],
    ["decode", ["VBT"]],
    ["deeded", ["VBD"]],
    ["deface", ["VBT"]],
    ["defats", ["VBZ"]],
    ["defeat", ["VBT", "NN"]],
    ["defect", ["NN", "VBI"]],
    ["defied", ["VBD"]],
    ["defies", ["VBZ"]],
    ["deiced", ["VBD"]],
    ["deices", ["VBZ"]],
    ["deific", ["JJ"]],
    ["deists", ["NNS"]],
    ["deseed", ["VBT"]],
    ["desist", ["VBI"]],
    ["detect", ["VBT"]],
    ["detest", ["VBT"]],
    ["diacid", ["NN"]],
    ["dibbed", ["VBD"]],
    ["dicots", ["NNS"]],
    ["dieted", ["VBD"]],
    ["diodes", ["NNS"]],
    ["discos", ["NNS"]],
    ["dissed", ["VBD", "JJ"]],
    ["disses", ["VBZ","NNS"]],
    ["dittos", ["NNS"]],
    ["doodad", ["NN"]],
    ["dotted", ["VBD", "JJ"]],
    ["eddied", ["VBD"]],
    ["eddies", ["VBZ","NNS"]],
    ["edicts", ["NNS"]],
    ["edited", ["VBD", "JJ"]],
    ["efface", ["VBT"]],
    ["effect", ["NN", "VBT"]],
    ["estate", ["NN"]],
    ["facade", ["NN"]],
    ["facets", ["NNS"]],
    ["facies", ["NNS"]],
    ["faeces", ["NNS"]],
    ["fascia", ["NN"]],
    ["fasted", ["VBD"]],
    ["fatted", ["JJ"]],
    ["feasts", ["VBZ","NNS"]],
    ["fiasco", ["NN"]],
    ["fibbed", ["VBD"]],
    ["fiesta", ["NN"]],
    ["fitted", ["VBD","JJ"]],
    ["fobbed", ["VBD"]],
    ["foetid", ["JJ"]],
    ["footed", ["VBD","JJ"]],
    ["ibises", ["NNS"]],
    ["iciest", ["JJS"]],
    ["idiots", ["NNS"]],
    ["iodide", ["NN"]],
    ["iodise", ["VBT"]],
    ["oboist", ["NN"]],
    ["obsess", ["VBT"]],
    ["octets", ["NNS"]],
    ["oddest", ["JJS"]],
    ["odessa", ["NNP"]],
    ["office", ["NN"]],
    ["offset", ["NN", "VBT", "VBI"]],
    ["ootids", ["NNS"]],
    ["otitis", ["NN"]],
    ["sadist", ["NN"]],
    ["safest", ["JJS"]],
    ["sassed", ["VBD"]],
    ["sasses", ["VBZ"]],
    ["scoffs", ["NNS","VBZ"]],
    ["scoots", ["NNS","VBZ"]],
    ["seabed", ["NN"]],
    ["seated", ["VBD","JJ"]],
    ["seccos", ["NNS"]],
    ["secede", ["VBI"]],
    ["sedate", ["JJ", "VBT"]],
    ["seeded", ["VBD","JJ"]],
    ["sestet", ["NN"]],
    ["settee", ["NN"]],
    ["siesta", ["NN"]],
    ["sifted", ["VBD"]],
    ["sobbed", ["VBD"]],
    ["sodded", ["VBD"]],
    ["soffit", ["NN"]],
    ["softie", ["NN"]],
    ["sooted", ["VBD","JJ"]],
    ["staffs", ["VBZ","NNS"]],
    ["stasis", ["NN"]],
    ["stated", ["VBD","JJ"]],
    ["states", ["VBZ","NNS"]],
    ["static", ["JJ", "NN"]],
    ["steeds", ["NNS"]],
    ["stiffs", ["VBZ","NNS"]],
    ["stoics", ["NNS"]],
    ["tabbed", ["VBD"]],
    ["taboos", ["NNS"]],
    ["tactic", ["JJ", "NN"]],
    ["tasted", ["VBD"]],
    ["tastes", ["VBZ","NNS"]],
    ["tatoos", ["?"]],
    ["tattoo", ["NN", "VBT"]],
    ["teased", ["VBD"]],
    ["teases", ["VBZ","NNS"]],
    ["teated", ["VBD"]],
    ["tested", ["VBD", "JJ"]],
    ["testes", ["NNS"]],
    ["tibiae", ["NNS"]],
    ["tibias", ["NNS"]],
    ["tictac", ["NN"]],
    ["tictoc", ["?"]],
    ["tidbit", ["NN"]],
    ["tidied", ["VBD"]],
    ["tidies", ["VBZ"]],
    ["toasts", ["VBZ","NNS"]],
    ["toffee", ["NN"]],
    ["tooted", ["VBD"]],
    ["tossed", ["VBD"]],
    ["tosses", ["VBZ","NNS"]],
    ["tsetse", []],
    ["abs", ["NNS"]],
    ["ace", ["NN", "VBT", "JJ"]],
    ["act", ["NN", "VBT", "VBI"]],
    ["ado", ["NN"]],
    ["ads", ["NNS"]],
    ["aft", ["RB", "JJ"]],
    ["aid", ["VBT", "VBI", "NN"]],
    ["ais", ["NNS"]],
    ["ate", ["NN"]],
    ["bad", ["JJ"]],
    ["bat", ["VBI", "NN", "VBT"]],
    ["bed", ["NN", "VBT", "VBI"]],
    ["bet", ["NN", "VBT", "VBI"]],
    ["bid", ["VBT", "VBI", "NN"]],
    ["bit", ["VBT", "NN"]],
    ["boa", ["NN"]],
    ["cab", ["NN"]],
    ["cad", ["NN"]],
    ["cat", ["NN"]],
    ["cis", ["JJ"]],
    ["cob", ["NN"]],
    ["cod", ["NN"]],
    ["cot", ["NN"]],
    ["dab", ["VBT", "VBI", "NN"]],
    ["die", ["VBI", "NN", "VBT"]],
    ["doe", ["NN"]],
    ["dos", ["NNS"]],
    ["dot", ["VBT", "VBI", "NN"]],
    ["eat", ["VBT", "VBI", "NN"]],
    ["efs", ["NNS"]],
    ["eta", ["NN"]],
    ["fad", ["NN"]],
    ["fat", ["JJ", "NN", "VBT"]],
    ["fed", ["VBD"]],
    ["fib", ["NN", "VBI"]],
    ["fit", ["JJ", "VBT", "VBI", "NN"]],
    ["foe", ["NN"]],
    ["ice", ["NN", "VBT", "VBI"]],
    ["ide", ["NN"]],
    ["ids", ["NNS"]],
    ["ifs", ["NNS"]],
    ["its", ["?"]],
    ["oaf", ["NN"]],
    ["oat", ["NN"]],
    ["ode", ["NN"]],
    ["oft", ["RB"]],
    ["sac", ["NN"]],
    ["sad", ["JJ"]],
    ["sat", ["VBD"]],
    ["sea", ["NN"]],
    ["set", ["VBT", "VBI", "JJ", "NN"]],
    ["sit", ["VBT", "VBI", "NN"]],
    ["sob", ["VBT", "VBI", "NN"]],
    ["sod", ["VBT", "NN"]],
    ["sot", ["NN"]],
    ["tab", ["NN", "VBT"]],
    ["tad", ["NN"]],
    ["tea", ["NN"]],
    ["tic", ["NN"]],
    ["tie", ["NN", "VBT", "VBI"]],
    ["toe", ["NN", "VBT", "VBI"]]
  ]
#  p WORDS_POS.map { |i| i[1] }.flatten.sort.uniq
#  p WORDS_POS.count
end

################################################################################
